### PR TITLE
Update pycaruna.py

### PR DESCRIPTION
**Pull request by mikafin**
Seems that Caruna has changed the API authentication. This seems to fix these issues.

### CODE REVIEW

**Comment by Jalle19** [comment]
I wish I'd seen this earlier, spent my afternoon coming to pretty much the same solution as you. See https://github.com/Jalle19/pycaruna/commit/11087294df22f3b6df0ac81995525976064f69ca

**Comment by kimmolinna** [comment]
And I didn't notice these two and did my own solution

**Comment by kimmolinna** [comment]
Sorry @mikafin. I just added License file and noticed then that Caruna has changed the API authentication and added an extra http post for it. I didn't mean to be rude but it was easier to update with my own code and decline your pull request.

**Comment by mikafin** [comment]
No problem 👍 Clad that it's fixed now.

**Pull request closed without merging**
